yfitTraceback (most recent call last):
  File "/home/site/KayAppServer/KayAppServer/views.py", line 2430, in send_give_him_order
    free=cort_to_list(cursor.fetchall())[0];
IndexError: list index out of range
